# HDC Module development

In [1]:
import torch
import torch.nn as nn

In [190]:
input = torch.ones((1,5,5))
kern = torch.ones([1, 1, 3, 3])# * torch.Tensor([1,2,3])
kern

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [198]:
c1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2,dilation=1, padding=(1,1))
c2 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, dilation=1, padding="valid")


with torch.no_grad():
   c1.weight = nn.Parameter(kern)
   c2.weight = nn.Parameter(kern)
   c1.bias = nn.Parameter(torch.Tensor([0]))
   c2.bias = nn.Parameter(torch.Tensor([0]))

input = torch.rand((1,7,7)).round(decimals=0)#(torch.ones((1,10,10)) * 1)

out1 = c1(input)
out2 = c2(input)

from matplotlib import pyplot as plt
input.shape, out1.shape, out2.shape

ValueError: padding='same' is not supported for strided convolutions

In [194]:
print(input)
print()
print(out1)
print()
print(out2)
print()


tensor([[[0., 1., 0., 0., 1., 1., 1.],
         [1., 0., 1., 0., 1., 0., 1.],
         [1., 0., 0., 0., 1., 1., 0.],
         [1., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 1., 1., 1., 1.],
         [1., 1., 1., 1., 0., 0., 1.],
         [0., 1., 0., 1., 1., 0., 1.]]])

tensor([[[1., 1., 3., 3., 3., 2., 3.],
         [3., 1., 5., 2., 5., 2., 4.],
         [1., 2., 4., 5., 5., 4., 5.],
         [5., 3., 7., 4., 7., 3., 5.],
         [1., 3., 4., 5., 5., 4., 5.],
         [3., 3., 4., 4., 4., 3., 3.],
         [0., 3., 2., 4., 4., 3., 4.]]], grad_fn=<SqueezeBackward1>)

tensor([[[4., 5., 5.],
         [7., 4., 7.],
         [4., 5., 5.]]], grad_fn=<SqueezeBackward1>)

