# HDC Module development

In [2]:
import torch
import torch.nn as nn

In [190]:
input = torch.ones((1,5,5))
kern = torch.ones([1, 1, 3, 3])# * torch.Tensor([1,2,3])
kern

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

In [199]:
c1 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, stride=2,dilation=1, padding=(1,1))
c2 = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=3, dilation=1, padding="valid")


with torch.no_grad():
   c1.weight = nn.Parameter(kern)
   c2.weight = nn.Parameter(kern)
   c1.bias = nn.Parameter(torch.Tensor([0]))
   c2.bias = nn.Parameter(torch.Tensor([0]))

input = torch.rand((1,7,7)).round(decimals=0)#(torch.ones((1,10,10)) * 1)

out1 = c1(input)
out2 = c2(input)

from matplotlib import pyplot as plt
input.shape, out1.shape, out2.shape

(torch.Size([1, 7, 7]), torch.Size([1, 4, 4]), torch.Size([1, 5, 5]))

In [194]:
print(input)
print()
print(out1)
print()
print(out2)
print()


tensor([[[0., 1., 0., 0., 1., 1., 1.],
         [1., 0., 1., 0., 1., 0., 1.],
         [1., 0., 0., 0., 1., 1., 0.],
         [1., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 1., 1., 1., 1.],
         [1., 1., 1., 1., 0., 0., 1.],
         [0., 1., 0., 1., 1., 0., 1.]]])

tensor([[[1., 1., 3., 3., 3., 2., 3.],
         [3., 1., 5., 2., 5., 2., 4.],
         [1., 2., 4., 5., 5., 4., 5.],
         [5., 3., 7., 4., 7., 3., 5.],
         [1., 3., 4., 5., 5., 4., 5.],
         [3., 3., 4., 4., 4., 3., 3.],
         [0., 3., 2., 4., 4., 3., 4.]]], grad_fn=<SqueezeBackward1>)

tensor([[[4., 5., 5.],
         [7., 4., 7.],
         [4., 5., 5.]]], grad_fn=<SqueezeBackward1>)



In [8]:
i = torch.rand((2, 10, 48, 256, 256))

sig = nn.Sigmoid()
soft = nn.Softmax(dim=1)

o = sig(i)
o2 = soft(o)

In [15]:
o2.max(dim=1).values.unique()

tensor([0.1013, 0.1014, 0.1015,  ..., 0.1197, 0.1199, 0.1201])

In [16]:
from src.Model.OrganNet25D import OrganNet25D

In [17]:
model = OrganNet25D()

Initialising organNet with (1, 2, 3)


In [21]:
for layer in model.children():
    print(layer.grad)

AttributeError: 'Sequential' object has no attribute 'grad'